// src/models/Category.js
//
// Data access layer for the categories table.
// All SQL queries use parameterized statements to prevent SQL injection.
// Methods return null when no record is found (instead of throwing).
// Soft delete is handled via the deleted_at column.

'use strict';

const { pool } = require('../database/connection');

class Category {

    // Retrieve all active categories (not soft-deleted)
    static async findAll() {
        const [rows] = await pool.execute(
            'SELECT * FROM categories WHERE deleted_at IS NULL ORDER BY name ASC'
        );
        return rows;
        // pool.execute() returns [rows, fields]
        // We destructure to keep only rows
        // If the table is empty, rows is an empty array [] — not null, not an error
    }

    // Retrieve a single category by its primary key
    // Returns null if not found or soft-deleted
    static async findById(id) {
        const [rows] = await pool.execute(
            'SELECT * FROM categories WHERE id = ? AND deleted_at IS NULL',
            [id]
            // The ? placeholder is replaced by the value in the array
            // mysql2 handles escaping — no manual sanitization needed here
        );
        return rows[0] || null;
        // rows[0] is undefined if no result → we return null explicitly
        // Callers can do: if (!category) { ... } cleanly
    }

    // Create a new category
    // Automatically generates a URL-friendly slug from the name
    // Returns the created category object (with its generated id)
    static async create({ name }) {
        const slug = name
            .toLowerCase()
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '') // strip accents
            .replace(/[^a-z0-9]+/g, '-')     // non-alphanumeric → hyphen
            .replace(/^-|-$/g, '');           // trim leading/trailing hyphens

        const [result] = await pool.execute(
            'INSERT INTO categories (name, slug) VALUES (?, ?)',
            [name, slug]
        );
        // result.insertId contains the auto-incremented id generated by MariaDB
        return Category.findById(result.insertId);
    }

    // Update the name of an existing category
    // Regenerates the slug to stay consistent with the new name
    // Returns the updated category, or null if it didn't exist
    static async update(id, { name }) {
        const slug = name
            .toLowerCase()
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, '');

        await pool.execute(
            `UPDATE categories
             SET name = ?, slug = ?
             WHERE id = ? AND deleted_at IS NULL`,
            [name, slug, id]
        );
        return Category.findById(id);
    }

    // Soft delete: sets deleted_at instead of removing the row
    // Why soft delete? It preserves referential integrity with recipes
    // that reference this category. A hard delete would break those relations
    // or require cascading deletes — dangerous in production.
    static async delete(id) {
        const [result] = await pool.execute(
            'UPDATE categories SET deleted_at = NOW() WHERE id = ? AND deleted_at IS NULL',
            [id]
        );
        // result.affectedRows tells us if the row actually existed
        return result.affectedRows > 0;
        // Returns true if deleted, false if the id didn't exist or was already deleted
    }
}

module.exports = Category;
